module.exports = {
  URLs: "https://perfeng-frontend.herokuapp.com",
  URL: "http://localhost:3000",
  screenshotPath: "./screenshots",
  dataTestAttribute: (value) => `[data-test-id=${value}]`,
  metricKeys: [
    "Timestamp",
    "Documents",
    "Frames",
    "JSEventListeners",
    "Nodes",
    "LayoutCount",
    "RecalcStyleCount",
    "LayoutDuration",
    "RecalcStyleDuration",
    "ScriptDuration",
    "TaskDuration",
    "JSHeapUsedSize",
    "JSHeapTotalSize",
  ],
  edrEndpoint: "https://qa-analytics-boot.herokuapp.com/saveEdr",
};
